### ISSUE TITLE
Document/link to withLabel options

### ISSUE THREAD

**Issue by reedy** [vector76/Web_OpenSCAD_Customizer#11]
I'm pretty new to the gridfinity stuff, and I'm strugging to work out the actual difference between the `withLabel` variants...

Is it documented somewhere? Can we include docs on https://vector76.github.io/Web_OpenSCAD_Customizer/gridfinity_bins.html ?

**Comment by vector76** [comment]
Good suggestion.  I made an attempt at documenting with a tooltip next to the field.  As part of 27c60af6a867d02766c85e14cdb3750d8a4e5425
