### ISSUE TITLE
Allow CTRL + Enter on params by using semantic form elements

### ISSUE THREAD

**Issue by waynevanson** [vector76/Web_OpenSCAD_Customizer#5]
I can't CTRL + ENTER on the input boxes because it's not a form.

I'm happy to fix.

**Comment by vector76** [comment]
Looks like this was a bit more than just form instead of div.  This is a bit beyond my depth but with the help of ChatGPT I think I got it.  Since the fields are not multi-line textareas, just ENTER and not CTRL+ENTER submits the form.

fc5835d3bc4bacd9ef058e2c1efbffefef86b209
