### ISSUE TITLE
Add missing license

### ISSUE THREAD

**Issue by timharek** [vector76/Web_OpenSCAD_Customizer#7]
First of all, thank you for this awesome project! It's been a massive time-saver for my Gridfinity 3D-printing.

Is it possible for you, @vector76, to add a license to this project? As of now this project is only source-available, which means legally no one can fork this project without your permission.

Check out https://choosealicense.com is you need inspiration/help to choose a license 😊

**Comment by vector76** [comment]
I've added a license.

For my part, I would be willing to license the project as MIT-style license but the bulk of the source is cloned from https://github.com/ochafik/openscad-wasm which is licensed GPL-2.0, so I have no choice but to apply the same license.
