### ISSUE TITLE
No scroll bars; have to zoom to see entire page

### ISSUE THREAD

**Issue by reedy** [vector76/Web_OpenSCAD_Customizer#9]
When I visit https://vector76.github.io/Web_OpenSCAD_Customizer/gridfinity_bins.html, there's no scroll bars and the page length is bigger than my viewing area... I have to zoom to 67% to be able to see everything

![image](https://github.com/user-attachments/assets/c3151799-9f40-410a-b650-c7a456d252a0)

![image](https://github.com/user-attachments/assets/3ee84705-0dac-41dd-9a04-3adc771235f1)

Not sure if it's done purposefully, but it's a little annoying.

Thanks!

**Comment by vector76** [comment]
Thank you for pointing this out.  I think this is fixed by 27fcd5cc0965d329fe867ac65acd2015039232ce

Full disclosure: I don't know what I'm doing, and I just did trial and error with ChatGPT.  It looks better to me.
